/**
 * The icon set available to a Super Admin when customizing a module's
 * appearance in the Designer. lucide-react ships 1000+ icons; this is a
 * curated ~90-icon subset relevant to business/CRM contexts (not literally
 * every icon in the library, which would make the picker unusable) —
 * "maximum set" here means broad coverage of what a business app actually
 * needs, not an exhaustive dump. Add to ICONS below if a genuinely new
 * category of module needs a glyph that isn't covered.
 *
 * Icons are looked up by string name (stored in moduleAppearance.ts's
 * JSON store), never passed as component references — components aren't
 * serializable across Server/Client boundaries, same reason every other
 * "type" field in this codebase is a string, not a function.
 */

import {
  ShoppingCart,
  Wrench,
  Receipt,
  Building2,
  Stethoscope,
  UtensilsCrossed,
  Users,
  Home,
  CalendarDays,
  GraduationCap,
  Factory,
  Truck,
  Scale,
  PartyPopper,
  Warehouse,
  FileSpreadsheet,
  Gift,
  UserCog,
  Store,
  Boxes,
  Briefcase,
  ClipboardList,
  CreditCard,
  DollarSign,
  IndianRupee,
  BarChart3,
  LineChart,
  PieChart,
  LayoutDashboard,
  Settings,
  ShieldCheck,
  KeyRound,
  Bell,
  Mail,
  Phone,
  MapPin,
  Calendar,
  Clock,
  FileText,
  FolderOpen,
  Package,
  PackageCheck,
  ClipboardCheck,
  BadgeCheck,
  Star,
  Tag,
  Tags,
  Percent,
  Wallet,
  Landmark,
  Building,
  Hospital,
  Car,
  Bike,
  Bus,
  Plane,
  Ship,
  Wifi,
  Globe,
  Link2,
  Database,
  Server,
  Cloud,
  Layers,
  Grid3x3,
  List,
  Table,
  Kanban,
  Workflow,
  GitBranch,
  Network,
  Handshake,
  UserCheck,
  UserPlus,
  Scissors,
  Dumbbell,
  BookOpen,
  Pill,
  Syringe,
  HeartPulse,
  Hammer,
  HardHat,
  Ruler,
  PaintBucket,
  Palette,
  Camera,
  Image,
  Video,
  Music,
  Coffee,
  Utensils,
  Beef,
  Shirt,
  Gem,
  Watch,
  Smartphone,
  Laptop,
  Printer,
  type LucideIcon,
} from "lucide-react";

export const ICONS: Record<string, LucideIcon> = {
  ShoppingCart,
  Wrench,
  Receipt,
  Building2,
  Stethoscope,
  UtensilsCrossed,
  Users,
  Home,
  CalendarDays,
  GraduationCap,
  Factory,
  Truck,
  Scale,
  PartyPopper,
  Warehouse,
  FileSpreadsheet,
  Gift,
  UserCog,
  Store,
  Boxes,
  Briefcase,
  ClipboardList,
  CreditCard,
  DollarSign,
  IndianRupee,
  BarChart3,
  LineChart,
  PieChart,
  LayoutDashboard,
  Settings,
  ShieldCheck,
  KeyRound,
  Bell,
  Mail,
  Phone,
  MapPin,
  Calendar,
  Clock,
  FileText,
  FolderOpen,
  Package,
  PackageCheck,
  ClipboardCheck,
  BadgeCheck,
  Star,
  Tag,
  Tags,
  Percent,
  Wallet,
  Landmark,
  Building,
  Hospital,
  Car,
  Bike,
  Bus,
  Plane,
  Ship,
  Wifi,
  Globe,
  Link2,
  Database,
  Server,
  Cloud,
  Layers,
  Grid3x3,
  List,
  Table,
  Kanban,
  Workflow,
  GitBranch,
  Network,
  Handshake,
  UserCheck,
  UserPlus,
  Scissors,
  Dumbbell,
  BookOpen,
  Pill,
  Syringe,
  HeartPulse,
  Hammer,
  HardHat,
  Ruler,
  PaintBucket,
  Palette,
  Camera,
  Image,
  Video,
  Music,
  Coffee,
  Utensils,
  Beef,
  Shirt,
  Gem,
  Watch,
  Smartphone,
  Laptop,
  Printer,
};

export const ICON_NAMES = Object.keys(ICONS).sort();

export function getIconComponent(name: string | undefined): LucideIcon | undefined {
  if (!name) return undefined;
  return ICONS[name];
}
